[build]
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

# Handle API routes with Netlify functions
[[redirects]]
  from = "/api/platform-data"
  to = "/.netlify/functions/platform-data"
  status = 200
  force = true

[[redirects]]
  from = "/api/countries-with-data"
  to = "/.netlify/functions/countries-with-data"
  status = 200
  force = true

# Let Next.js handle routing - no catch-all redirect needed

[dev]
  command = "npm run dev"
  port = 3000
  publish = "out"

# Headers for better performance and security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
